replicaCount: 2

image:
  repository: 178502900821.dkr.ecr.ap-south-1.amazonaws.com/devops-demo
  tag: 27cd905de75289c2151d94d5924491cebac34b48
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  APP_VERSION: "v1-gitops"
  ENV: "gitops"
